# Generated by Django 4.0.8 on 2022-10-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_coupon_created_at_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
